### ISSUE TITLE
Plugin not listed in event settings

### ISSUE THREAD

**Issue by kc9ryt** [pretix/pretix-bounces#4]
Hello,
This plugin does not appear to be working. I have enabled it and can see it in the admin mode on the updates page but when i go to an event there is no plugin listed?

**Comment by pc-coholic** [comment]
Hello there!

This plugin is working side-wide - you only have to install it and then configure it as described in the README using your pretix.cfg-file.

It will be active for all events then - but not show up in the list of dis-/enabled plugins.

**Comment by kc9ryt** [comment]
Hello,
Is there a way to check to see if the plugin is actually talking to the mailbox? I purchased a ticket and got an email but it was just the normal no-reply@domain.com and replied to it but my response never showed in pretix.

**Comment by pc-coholic** [comment]
Assuming your `pretix.cfg` looks like this:
```
[bounces]
alias=noreply-%s@mydomain.com
server=mail.mydomain.com:993
user=noreply@mydomain.com
pass=12345678
```
all order-related emails you receive should have a `Sender`-header that looks something like `noreply-amCwRFatawEjetS8@pretix.eu`. The `From` and `Reply To` stay unchanged.
